dns:
  # only supports dnspod for now
  type: dnspod
  params:
    domain: example.com
    id: secretid
    key: secretkey

mc_router_baseurl: http://localhost:26666

natmap_monitor:
  enabled: true
  baseurl: http://localhost:8090
docker_watcher:
  enabled: true
  baseurl: http://localhost:8091

managed_sub_domain: "mc"

dns_ttl: 600

addresses:
  "*":
    type: natmap
    params:
      internal_port: 25565
  "backup":
    type: manual
    params:
      record_type: "CNAME"
      value: "backupdomain.com"
      port: 25565

poll_interval: 15
logging_level: INFO
